name: OWASP ZAP Integration with GitHub Actions

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web applications
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      # Step 2: Log in to Docker Hub (optional, if using private Docker images)
      # Uncomment the following block if Docker login is required.
      # - name: Log in to Docker Hub
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'owasp/zap2docker-weekly'  # Updated to use the correct weekly image
          target: 'http://testphp.vulnweb.com/'
          cmd_options: '-a'  # Remove 'rules_file_name' if not using custom rules
